export const ABOUT_DATA = [
  {
    imageSrc: 'assets/story-imgs/moe-anko.jpg',
    jobTitle: 'about.PERSON_JOB_TITLE_OWNER',
    name: 'about.MOE_NAME',
    description: 'about.MOE_DESCRIPTION',
    borderColor: 'border-pink-400',
    backgroundColor: 'bg-pink-400',
    buttonColor: 'border-pink-400',
    textColor: 'text-pink-400',
  },
  {
    imageSrc: 'assets/story-imgs/juan.jpg',
    jobTitle: 'about.PERSON_JOB_TITLE_MANAGER',
    name: 'about.JUAN_NAME',
    description: 'about.JUAN_DESCRIPTION',
    borderColor: 'border-emerald-500',
    backgroundColor: 'bg-emerald-500',
    buttonColor: 'border-emerald-500',
    textColor: 'text-emerald-400',
  },
  {
    imageSrc: 'assets/story-imgs/moko.jpg',
    jobTitle: 'about.PERSON_JOB_TITLE_CAT',
    name: 'about.MOKO_NAME',
    description: 'about.MOKO_DESCRIPTION',
    borderColor: 'border-orange-400',
    backgroundColor: 'bg-orange-400',
    buttonColor: 'border-orange-400',
    textColor: 'text-orange-400',
  },
  {
    imageSrc: 'assets/story-imgs/family.jpg',
    jobTitle: 'about.PERSON_JOB_TITLE_FAMILY',
    name: 'about.FAMILY_NAME',
    description: 'about.FAMILY_DESCRIPTION',
    borderColor: 'border-cyan-400',
    backgroundColor: 'bg-cyan-400',
    buttonColor: 'border-cyan-400',
    textColor: 'text-cyan-400',
  },
];
